version: 0.2

env:
  variables:
    REPOSITORY_URI : "947355239983.dkr.ecr.us-west-1.amazonaws.com/angular-app-testing-aws-codepipeline"
    IMAGE_NAME : "angular-app-testing-aws-codepipeline"
    IMAGE_VERSION : "latest"


phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-1)
      - echo Get commit ID
      - COMMIT_HASH="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag $IMAGE_NAME:$COMMIT_HASH-$IMAGE_VERSION .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tag the Docker image...
      - docker tag $IMAGE_NAME:$COMMIT_HASH-$IMAGE_VERSION $REPOSITORY_URI:$COMMIT_HASH-$IMAGE_VERSION
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_HASH-$IMAGE_VERSION
